select * from products
--Phase 1: Business Overview (Basic KPIs)
--Q!.What is the total revenue generated by the company?
select sum(payment_value) as revenue 
from order_payments

--Q2.How many orders has the company received?
select count(order_id) as total_orders
from orders

--Q3.How many unique customers has the company served?
select count(distinct customer_unique_id) as unique_customers
from customers

--Q4.Which are the Top 10 states with the highest number of customers?
select customer_state,count(distinct customer_unique_id) as unique_customers
from customers
group by customer_state
order by unique_customers desc
limit 10

--Q5.Which states have generated the highest number of orders? (Top 10)
select c.customer_state,count(o.order_id) as total_orders
from customers c
join orders o
on o.customer_id=c.customer_id
group by c.customer_state
order by total_orders desc
limit 10

--Q6.What are the Top 10 Product Categories by Revenue?
select t.product_category_name_english,sum(o.price) as total_revenue
from order_items o
join products p
on o.product_id=p.product_id
join product_category_name t
on t.product_category_name=p.product_category_name
group by t.product_category_name_english
order by total_Revenue desc
limit 10

--Q7.Find the Top 10 Customers by Total Spending.
SELECT
    c.customer_unique_id,
    SUM(op.payment_value) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spending DESC
LIMIT 10;

--8.What is the Average Order Value (AOV) of the company?
select sum(payment_value)/count(distinct order_id) as aov 
from order_payments

--Q9.Show the number of orders by each order status.
select order_status,count(order_id) as no_of_orders
from orders
group by order_status
order by no_of_orders  desc

--10.Find the Top 10 Sellers by Total Revenue.
select s.seller_id,sum(oi.price) as revenue
from sellers s
join order_items oi 
on s.seller_id=oi.seller_id
group by s.seller_id
order by revenue desc
limit 10

--11.Find the Monthly Revenue Trend.
SELECT
    EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,
    EXTRACT(MONTH FROM o.order_purchase_timestamp) AS month,
    ROUND(SUM(op.payment_value), 2) AS total_revenue
FROM orders o
JOIN order_payments op
ON o.order_id = op.order_id
GROUP BY
    EXTRACT(YEAR FROM o.order_purchase_timestamp),
    EXTRACT(MONTH FROM o.order_purchase_timestamp)
ORDER BY year, month;

--Q12. Total Freight Charges
SELECT SUM(freight_value) AS total_freight
FROM order_items;

--Q13. Average Review Score
SELECT AVG(review_score) AS average_review_score
FROM olive_reviews;

--Phase 2: Logistics and Operations
--1. Average delivery time
select * from orders
SELECT
AVG(
    (order_delivered_customer_date -
     order_purchase_timestamp)
) AS avg_delivery_time
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
SELECT
order_purchase_timestamp,
order_delivered_customer_date
FROM orders
LIMIT 5;

ALTER TABLE orders
ALTER COLUMN order_purchase_timestamp
TYPE timestamp
USING to_timestamp(order_purchase_timestamp,'DD-MM-YYYY HH24:MI');

ALTER TABLE orders
ALTER COLUMN order_delivered_customer_date
TYPE timestamp
USING to_timestamp(order_delivered_customer_date,'DD-MM-YYYY HH24:MI');

ALTER TABLE orders
ALTER COLUMN order_approved_at
TYPE timestamp
USING to_timestamp(order_approved_at,'DD-MM-YYYY HH24:MI');

ALTER TABLE orders
ALTER COLUMN order_delivered_carrier_date
TYPE timestamp
USING to_timestamp(order_delivered_carrier_date,'DD-MM-YYYY HH24:MI');

ALTER TABLE orders
ALTER COLUMN order_estimated_date
TYPE timestamp
USING to_timestamp(order_estimated_date,'DD-MM-YYYY HH24:MI');

--2.avg shipping days (ie avg seller processing time)
select avg(order_delivered_carrier_date - order_approved_at) as avg_shipping_Days
from orders 
where order_delivered_carrier_date is not null;

--3.avg delivery delay?
select avg(order_delivered_customer_date-order_estimated_date) as avg_delay_days
from orders --early delivery 

--4.States with highest delivery delay
select c.customer_state,avg(o.order_delivered_customer_date - o.order_estimated_date) as delivery_delay
from customers c
join orders o 
on c.customer_id=o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
group by c.customer_state
order by delivery_delay desc
limit 5

--5.Monthly delivery trend
select * from order_items
select extract(year from order_purchase_timestamp) as year,
extract(month from order_purchase_timestamp) as month,
avg(order_delivered_customer_date - order_estimated_date) as delivery_delay
from orders
where order_delivered_customer_date IS NOT NULL
group by extract(year from order_purchase_timestamp),extract(month from order_purchase_timestamp)
order by year,month

--6.Top sellers by number of orders
select s.seller_id,sum(oi.order_item_id) as total_orders
from sellers s
join order_items oi
on s.seller_id=oi.seller_id
group by s.seller_id
order by sum(oi.order_item_id) desc
limit 5

--7. Average delivery time by seller (slow sellers)
select oi.seller_id,avg(o.order_delivered_carrier_date - o.order_approved_at) as delivery_time_by_seller
from order_items oi
join orders o
on oi.order_id=o.order_id
WHERE o.order_delivered_customer_date IS NOT NULL
group by oi.seller_id
order by delivery_time_by_seller desc
limit 5;

--8.Sellers with highest freight cost
select seller_id,round(sum(freight_value)::numeric,2) as frieght_cost
from order_items
group by seller_id
order by frieght_cost desc
limit 5;

--9. Average freight cost per order
select avg(total_freight) as avg_freight 
from(
   select order_id,sum(freight_value) as total_freight
   from order_items
   group by order_id
)t

--10. Product categories with highest freight charges
select p.product_category_name,round(sum(oi.freight_value)::numeric,2) as total_freight,pc.product_category_name_english
from products p
join order_items oi
on p.product_id=oi.product_id
join product_category_name pc
on p.product_category_name=pc.product_category_name
group by p.product_category_name,pc.product_category_name_english
order by total_freight desc
limit 5;

--11. Freight as a Percentage of Product Price by Product Category
SELECT
    t.product_category_name_english,
    SUM(oi.freight_value) * 100.0 / SUM(oi.price)
        
    AS freight_percentage
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN product_category_name t
    ON p.product_category_name = t.product_category_name
GROUP BY t.product_category_name_english
ORDER BY freight_percentage DESC;

--12. Review score vs delivery delay
CREATE VIEW review_vs_delivery AS
select
 case
   when o.order_delivered_customer_date <= o.order_estimated_date then 'on time'
   when o.order_delivered_customer_date >= o.order_estimated_date + interval '3 days' then '1-3 day delay'
   when o.order_delivered_customer_date >= o.order_estimated_date + interval '5 days' then '4-7 days delay'
   else '>7 days delay'
 end as delivery_status,
 round(avg(r.review_score)::numeric,2) as avg_review_Score
 from orders o
 join olive_reviews r
 on o.order_id=r.order_id
 group by delivery_status
 
 --13.Orders delivered on time vs delayed
select 
case
when order_delivered_customer_date <= order_estimated_date then 'on time'
else 'late delivery'
end as delivery_status,
count(order_id) as total_orders,
ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
from orders
group by delivery_status

--14.14. Cancellation rate
select 
sum(case when order_status='canceled' then 1 else 0 end )as cancelled_orders,count(*) as total_orders,
sum(case
when order_status='canceled' then 1 else 0 end)*100.0/count(*) as cancellation_rte
from orders 

--Regional detail
--15.Revenue by state
select c.customer_state , round(sum(op.payment_value)::numeric,2) as total_revenue
from order_payments op
join orders o 
on op.order_id=o.order_id
join customers c
on  o.customer_id=c.customer_id
group by c.customer_state
order by total_revenue desc

--16.Delivery time by state
select c.customer_state, (order_delivered_customer_date - order_purchase_timestamp) as delivery_time
from orders o
join customers c
on c.customer_id=o.customer_id
and order_delivered_customer_date is not null
order by delivery_time desc
limit 10

--17.Freight cost by state
select c.customer_state,oi.freight_value
from order_items oi
join orders o
on oi.order_id=o.order_id
join customers c
on o.customer_id=c.customer_id
order by oi.freight_value desc
limit 10

--Product Analysis
--18. Best-selling product categories
select p.product_category_name,pc.product_category_name_english,count(oi.product_id) as total_count
from products p
join order_items oi
on p.product_id=oi.product_id
join product_category_name pc
on p.product_category_name=pc.product_category_name
group by p.product_category_name,pc.product_category_name_english
order by total_count desc;

--19.Categories with highest average review
select pc.product_category_name_english,avg(o_r.review_score) as avg_review
from olive_reviews o_r
join order_items oi
on o_r.order_id=oi.order_id
join products p
on oi.product_id=p.product_id
join product_category_name pc
on p.product_category_name=pc.product_category_name
group by pc.product_category_name_english
order by avg_review desc

--20.Categories with longest delivery time
select pc.product_category_name_english,avg(o.order_delivered_customer_date - o.order_purchase_timestamp) as avg_delivery
from orders o
join order_items oi
on o.order_id=oi.order_id
join products p
on oi.product_id=p.product_id
join product_category_name pc
on p.product_category_name=pc.product_category_name 
WHERE o.order_delivered_customer_date IS NOT NULL
group by pc.product_category_name_english
order by avg_delivery desc